version: "3.7"

# Service Definitions
services:

  db:
    image: "amineo/t2-stats-db:v0.1.2"
    build:
      context: .
      dockerfile: ./build/postgres/Dockerfile
    environment:
      POSTGRES_DB: "t2_stats"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - psqldata:/var/lib/postgresql/data
    networks:
      - internal
    deploy:
      labels:
        - traefik.enable=false
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]      


  parser:
    image: "amineo/t2-stats-parser:v0.1.2"
    build:
      context: .
      dockerfile: ./build/go-t2-stat-parser/Dockerfile
    environment: 
      DATABASE_URL: "postgres://${POSTGRES_USER}:{POSTGRES_PASSWORD}@db:5432/t2_stats"
      FTP_HOST: "${FTP_HOST}"
      FTP_USER: "${FTP_USER}"
      FTP_PW: "${FTP_PW}"      
    depends_on:
      - db
    networks:
      - internal
      - external
    deploy:
      labels:
        - traefik.enable=false
      mode: replicated
      replicas: 1


volumes:
  psqldata:


networks:
  external:
  internal: