version: "3.7"

# Service Definitions
services:

  db:
    environment:
      POSTGRES_DB: "t2_stats"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
    volumes: 
      - ./build/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./build/postgres/export_local_db.sh:/export_local_db.sh    


  parser:
    environment: 
      DATABASE_URL: "postgres://dev:dev@db:5432/t2_stats"
    volumes:
      - ./app/t2-stat-parser:/app
