version: "3.7"

# Service Definitions
services:

  db:
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "t2_stats"


  parser:
    environment: 
      DATABASE_URL: "postgres://dev:dev@db:5432/t2_stats"
    volumes:
      - ./app/t2-stat-parser:/app
